## KNN Classifier (K-Nearest Neighbors)

In [1]:
# Experiment no.12

In [2]:
# Aim : To Perform the Operation of KNN_Classifiers

In [3]:
# Name : Mohini D. Tayade
# Roll no. : 60
# Subject : DSS
# Date :

In [4]:
#importing the basic library
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.pipeline import make_pipeline

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\Lenovo'

In [7]:
os.chdir("C:\\Users\\Lenovo\\Desktop")

In [8]:
data=pd.read_csv("heart.csv")

In [9]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [10]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [11]:
# Check missing values
data.isnull().sum().sum()
print("\nMissing Values:")
print(data.isnull().sum().sum())

Missing Values:
0

In [12]:
# Separate input and target
X = data.drop("target", axis=1)
y = data["target"]

In [13]:
# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
# Create KNN model with scaling
model = make_pipeline(
    StandardScaler(),
    KNeighborsClassifier(n_neighbors=5)
)

In [15]:
# Train the model
model.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('kneighborsclassifier', KNeighborsClassifier())])

In [16]:
# Make predictions
y_pred = model.predict(X_test)

In [17]:
# Evaluate the model
print("\nAccuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8032786885245902

In [18]:
accuracy_score(y_test, y_pred) * 100

80.32786885245902

In [19]:
# Confusion Matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[19  9]
 [ 3 30]]

In [20]:
# Classification Report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.68      0.76        28
           1       0.77      0.91      0.83        33

    accuracy                           0.80        61
   macro avg       0.82      0.79      0.80        61
weighted avg       0.81      0.80      0.80        61